vim.keymap.set("n", "-", "<cmd>Oil --float<CR>", { desc = "Open Oil File Explorer" })
vim.keymap.set("n", "<leader>q", "<cmd>bd<CR>", { desc = "Close Buffer" })
vim.keymap.set("n", "<leader>Q", "<cmd>bd!<CR>", { desc = "Force Close Buffer" })
vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>", { desc = "Clear highlights" })
vim.keymap.set("t", "<Esc><Esc>", "<C-\\><C-n>", { desc = "Exit terminal mode" })
vim.keymap.set("n", "<C-h>", "<C-w><C-h>", { desc = "Move focus to the left window" })
vim.keymap.set("n", "<C-l>", "<C-w><C-l>", { desc = "Move focus to the right window" })
vim.keymap.set("n", "<C-j>", "<C-w><C-j>", { desc = "Move focus to the lower window" })
vim.keymap.set("n", "<C-k>", "<C-w><C-k>", { desc = "Move focus to the upper window" })
vim.keymap.set("n", "gl", function()
  vim.diagnostic.open_float()
end, { desc = "Open Diagnostics" })
vim.keymap.set("n", "<leader>cf", function()
  require("conform").format()
end, { desc = "[C]ode [F]ormat current buffer" })

local harpoon = require("harpoon")
vim.keymap.set("n", "<leader>`", function()
  harpoon:list():add()
end, { desc = "Harpoon File" })
vim.keymap.set("n", "<C-e>", function()
  harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = "Toggle Harpoon" })

vim.keymap.set("n", "<leader>1", function()
  harpoon:list():select(1)
end)
vim.keymap.set("n", "<leader>2", function()
  harpoon:list():select(2)
end)
vim.keymap.set("n", "<leader>3", function()
  harpoon:list():select(3)
end)
vim.keymap.set("n", "<leader>4", function()
  harpoon:list():select(4)
end)

-- Toggle previous & next buffers stored within Harpoon list
vim.keymap.set("n", "<C-[>", function()
  harpoon:list():prev()
end)
vim.keymap.set("n", "<C-]>", function()
  harpoon:list():next()
end)

vim.keymap.set("i", "<C-y>", function()
  local vt = require("codeium.virtual_text")

  if vt.has_completion() then
    return vt.accept()
  end
  return "<C-y>"
end, { expr = true, silent = true, desc = "Accept Codeium suggestion" })
vim.keymap.set("n", "<leader>co", "<cmd>Codeium Toggle<CR>", { desc = "Toggle Codeium" })
